### ISSUE TITLE
Unwanted dependency on Router and Presenters

### ISSUE THREAD

**Issue by flokixdev** [mathematicator-core/calculator#6]
As we see in tests, we rely on Nette Router dependency because there is some in-build redirection to a SearchPresenter in FrontModule.

From my point of view, `nette/application` (MVC kernel) should not be a dependency of this package because it is not its purpose.

The purpose and responsibility of this package is computing.

The benefit would be that we can use this component in other scenarios without pain.

**Comment by janbarasek** [comment]
Good point, I will remove the dependency.
